"""estoque profissional por numeracao

Revision ID: 08bf0c9c54de
Revises: 91499ab2fbc3
Create Date: 2026-06-08 20:40:18.949466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08bf0c9c54de'
down_revision = '91499ab2fbc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_atualizacao', sa.DateTime(), nullable=True))
        batch_op.alter_column('numeracao',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoques', schema=None) as batch_op:
        batch_op.alter_column('numeracao',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('data_atualizacao')

    # ### end Alembic commands ###
