"""add mercado pago pix pedido

Revision ID: 12083d9f8170
Revises: e999afb72504
Create Date: 2026-06-20 12:09:38.969918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12083d9f8170'
down_revision = 'e999afb72504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mercado_pago_payment_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('pix_copia_cola', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pix_qr_code_base64', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pix_ticket_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('pix_ticket_url')
        batch_op.drop_column('pix_qr_code_base64')
        batch_op.drop_column('pix_copia_cola')
        batch_op.drop_column('mercado_pago_payment_id')

    # ### end Alembic commands ###
