"""add numeracao pedido item

Revision ID: 659aa368a659
Revises: 7f0864676e2f
Create Date: 2026-06-08 23:46:05.547207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659aa368a659'
down_revision = '7f0864676e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numeracao', sa.String(length=10), nullable=True))
        batch_op.alter_column('pedido_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('produto_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_itens', schema=None) as batch_op:
        batch_op.alter_column('produto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('pedido_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('numeracao')

    # ### end Alembic commands ###
