"""cria carrinho

Revision ID: 7f0864676e2f
Revises: bc1f82dea3d8
Create Date: 2026-06-08 22:39:55.441855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0864676e2f'
down_revision = 'bc1f82dea3d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrinho_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=120), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('numeracao', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carrinho_itens')
    # ### end Alembic commands ###
