"""add entrega pedido

Revision ID: 818b70137a34
Revises: 659aa368a659
Create Date: 2026-06-09 00:15:03.435950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818b70137a34'
down_revision = '659aa368a659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_entrega', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('valor_entrega', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('valor_entrega')
        batch_op.drop_column('tipo_entrega')

    # ### end Alembic commands ###
