"""produto profissional westlooks

Revision ID: 91499ab2fbc3
Revises: e7fb57f1a521
Create Date: 2026-06-08 20:37:30.674168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91499ab2fbc3'
down_revision = 'e7fb57f1a521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referencia', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('custo', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('frete_gratis', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('peso', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('altura', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('largura', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comprimento', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('visualizacoes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('visualizacoes')
        batch_op.drop_column('comprimento')
        batch_op.drop_column('largura')
        batch_op.drop_column('altura')
        batch_op.drop_column('peso')
        batch_op.drop_column('frete_gratis')
        batch_op.drop_column('custo')
        batch_op.drop_column('referencia')

    # ### end Alembic commands ###
