"""add rastreamento pedido

Revision ID: ae002744e569
Revises: 818b70137a34
Create Date: 2026-06-09 08:54:45.769957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae002744e569'
down_revision = '818b70137a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_rastreamento', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('transportadora', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('data_envio', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_entrega', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('data_entrega')
        batch_op.drop_column('data_envio')
        batch_op.drop_column('transportadora')
        batch_op.drop_column('codigo_rastreamento')

    # ### end Alembic commands ###
