"""categoria profissional westlooks

Revision ID: bc1f82dea3d8
Revises: 08bf0c9c54de
Create Date: 2026-06-08 20:41:22.763265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1f82dea3d8'
down_revision = '08bf0c9c54de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('imagem', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('destaque', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ordem', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_column('data_cadastro')
        batch_op.drop_column('ordem')
        batch_op.drop_column('destaque')
        batch_op.drop_column('imagem')
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
