"""add datas status pedido

Revision ID: d0aa1b96145d
Revises: ae002744e569
Create Date: 2026-06-15 10:39:25.434883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0aa1b96145d'
down_revision = 'ae002744e569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_pagamento', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_preparacao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('data_preparacao')
        batch_op.drop_column('data_pagamento')

    # ### end Alembic commands ###
