"""configuracoes loja

Revision ID: dc9049c20b18
Revises: d0aa1b96145d
Create Date: 2026-06-19 18:18:37.346332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9049c20b18'
down_revision = 'd0aa1b96145d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_loja', sa.String(length=200), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('tipo_pix', sa.String(length=50), nullable=True),
    sa.Column('chave_pix', sa.String(length=255), nullable=True),
    sa.Column('nome_recebedor', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
