"""mercado pago configuracoes

Revision ID: e999afb72504
Revises: dc9049c20b18
Create Date: 2026-06-20 11:15:36.283867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e999afb72504'
down_revision = 'dc9049c20b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mercado_pago_public_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mercado_pago_access_token', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_column('mercado_pago_access_token')
        batch_op.drop_column('mercado_pago_public_key')

    # ### end Alembic commands ###
